# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'FROM golang:1.16.4-buster AS builder  ARG VERSION=dev  WORKDIR /go/src/app COPY main.go . RUN go build -o main -ldflags=-X=main.version=${VERSION} main.go  FROM debian:buster-slim COPY --from=builder /go/src/app/main /go/bin/main ENV PATH=&quot;/go/bin:${PATH}&quot; CMD [&quot;main&quot;]'
        tags: |
          $(tag)
